apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: svtcw7j72-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: svtcw7j72-go 
  name: svtcw7j72-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: svtcw7j72-go 
